version: '3.8'

services:
  facebook-ai-agent:
    build: .
    container_name: facebook-ai-agent
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # If you need to expose any ports
    restart: unless-stopped
